version: '3.8'

services:
  vite:
    build: ./front
    image: node:alpine
    container_name: vite
    command: ["npm", "run", "dev", "--", "--host", "0.0.0.0"]
    volumes:
      - ./front/src:/app/src
    ports:
      - "5173:5173"

  app:
    build: ./back
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=postgresdb
      - DB_USER=myuser
      - DB_PASSWORD=mypassword
      - DB_NAME=mydatabase
      - DB_PORT=5432
    stdin_open: true
    tty: true
    volumes:
      - ./back/src:/app/src

volumes:
  db: